name: Deploy to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker build
        run: docker build -t super-mario-game .

      - name: Deploy infrastructure
        run: |
          # Assume Terraform is used for infra
          # az deployment group create --resource-group myrg --template-file template.json --parameters parameters.json

      - name: ACR login
        run: az acr login --name myacr

      - name: Push image
        run: docker push myacr.azurecr.io/super-mario-game

      - name: Deploy to hosting
        run: |
          # az containerapp create --name myapp --resource-group myrg --image myacr.azurecr.io/super-mario-game --ingress external --target-port 8080
